# [[plugins]]
# repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tpope/vim-surround'

# [[plugins]]
# repo = 'kassio/neoterm'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

# [[plugins]]
# repo = 'Jagua/vim-denite-ghq'

# [[plugins]]
# repo = 'junegunn/fzf.vim'

[[plugins]]
# https://mattn.kaoriya.net/software/lang/go/20181217000056.htm
repo = 'prabirshrestha/async.vim'

[[plugins]]
# https://mattn.kaoriya.net/software/lang/go/20181217000056.htm
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
# https://mattn.kaoriya.net/software/lang/go/20181217000056.htm
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
# https://mattn.kaoriya.net/software/lang/go/20181217000056.htm
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
# https://mattn.kaoriya.net/software/lang/go/20181217000056.htm
repo = 'natebosch/vim-lsc'

[[plugins]]
# https://qiita.com/takaakikasai/items/0d617b6e0aed490dff35
repo = 'rickhowe/diffchar.vim'
